instagram/urls.py
from django.urls import path
from . import views

app_name = "instagram"
urlpatterns = [
    path("", views.index, name="index"),
    path("post/", views.post, name="post"),
    path("update/<pk>/", views.update, name="update"),
    path("delete/<pk>/", views.delete, name="delete"),
    path("post_detail/<pk>/", views.post_detail, name="post_detail"),
    path("post_detail/<pk>/comment_create",
         views.comment_create, name="comment_create"),
    path("post_detail/<pk>/comment_delete/<comment_pk>/",
         views.comment_delete, name="comment_delete"),
    path("post_detail/<pk>/like/", views.like, name="like"),
    path("search/<search_for>", views.search, name="search"),
    path("profile/<username>/", views.profile, name="profile"),
    path("profile/<username>/follow/", views.follow, name="follow"),
    path("dm/", views.dm, name="dm"),
    path("notice/", views.notice, name="notice"),
    path("profile_edit/", views.profile_edit, name="profile_edit"),
    path("profile_edit/reset_profile_image",
         views.reset_profile_image, name="reset_profile_image"),
    path("change_password/", views.change_password, name="change_password"),
]

registration/urls.py
from django.urls import path
from . import views

app_name = "registration"
urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("delete_account/", views.delete_account, name="delete_account"),
]

instagram/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime, timedelta
from django.utils import timezone


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    user_image = models.ImageField(
        upload_to="image", null=True, blank=True, default="profile.jpg")
    name = models.CharField(max_length=50, blank=True)
    website = models.CharField(max_length=200, blank=True)
    introduction = models.TextField(blank=True)
    gender = models.CharField(max_length=20, default="conceal")
    custom_gender = models.CharField(max_length=12, blank=True)


class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    main_image = models.ImageField(upload_to="image", null=True)
    create_date = models.DateTimeField(auto_now_add=True)

    @property
    def create_date_string(self):
        time = datetime.now(tz=timezone.utc) - self.create_date

        if time < timedelta(minutes=1):
            return '방금 전'
        elif time < timedelta(hours=1):
            return str(int(time.seconds / 60)) + '분 전'
        elif time < timedelta(days=1):
            return str(int(time.seconds / 3600)) + '시간 전'
        elif time < timedelta(days=7):
            time = datetime.now(tz=timezone.utc).date() - \
                self.create_date.date()
            return str(time.days) + '일 전'
        elif time < timedelta(days=365):
            time = datetime.now(tz=timezone.utc).date() - \
                self.create_date.date()
            return str(time.days // 7) + '주'
        else:
            return f"{self.create_date.year}년 {self.create_date.month}월 {self.create_date.day}일"


class PostComment(models.Model):
    post = models.OneToOneField(Post, on_delete=models.CASCADE)
    text = models.TextField(blank=True)
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    @property
    def create_date_string(self):
        time = datetime.now(tz=timezone.utc) - self.create_date

        if time < timedelta(minutes=1):
            return '방금 전'
        elif time < timedelta(hours=1):
            return str(int(time.seconds / 60)) + '분 전'
        elif time < timedelta(days=1):
            return str(int(time.seconds / 3600)) + '시간 전'
        elif time < timedelta(days=7):
            time = datetime.now(tz=timezone.utc).date() - \
                self.create_date.date()
            return str(time.days) + '일 전'
        elif time < timedelta(days=365):
            time = datetime.now(tz=timezone.utc).date() - \
                self.create_date.date()
            return str(time.days // 7) + '주'
        else:
            return f"{self.create_date.year}년 {self.create_date.month}월 {self.create_date.day}일"


class PostTag(models.Model):
    post = models.ManyToManyField(Post, blank=True)
    text = models.TextField(unique=True)

    def __str__(self):
        return self.text


class Image(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="image", null=True)


class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)


class Follow(models.Model):
    follower = models.ForeignKey(
        User, related_name="follower", on_delete=models.CASCADE)
    following = models.ForeignKey(
        User, related_name="following", on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.follower} <= {self.following}"


class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    text = models.CharField(max_length=200)
    create_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text

    @property
    def create_date_string(self):
        time = datetime.now(tz=timezone.utc) - self.create_date

        if time < timedelta(minutes=1):
            return '방금 전'
        elif time < timedelta(hours=1):
            return str(int(time.seconds / 60)) + '분 전'
        elif time < timedelta(days=1):
            return str(int(time.seconds / 3600)) + '시간 전'
        elif time < timedelta(days=7):
            time = datetime.now(tz=timezone.utc).date() - \
                self.create_date.date()
            return str(time.days) + '일 전'
        elif time < timedelta(days=365):
            time = datetime.now(tz=timezone.utc).date() - \
                self.create_date.date()
            return str(time.days // 7) + '주'
        else:
            return f"{self.create_date.year}년 {self.create_date.month}월 {self.create_date.day}일"


class HashTag(models.Model):
    comment = models.ManyToManyField(Comment, blank=True)
    text = models.TextField(unique=True)

    def __str__(self):
        return self.text


class Notice(models.Model):
    TYPE_CHOICES = (
        ("like", "like"),
        ("comment", "comment"),
        ("follow", "follow"),
    )

    sender = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="sender")
    receiver = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="receiver")
    type = models.CharField(max_length=20, choices=TYPE_CHOICES)
    check = models.BooleanField(default=False)
    create_date = models.DateTimeField(auto_now_add=True)

    @property
    def create_date_string(self):
        time = datetime.now(tz=timezone.utc) - self.create_date

        if time < timedelta(minutes=1):
            return '방금 전'
        elif time < timedelta(hours=1):
            return str(int(time.seconds / 60)) + '분 전'
        elif time < timedelta(days=1):
            return str(int(time.seconds / 3600)) + '시간 전'
        elif time < timedelta(days=7):
            time = datetime.now(tz=timezone.utc).date() - \
                self.create_date.date()
            return str(time.days) + '일 전'
        elif time < timedelta(days=365):
            time = datetime.now(tz=timezone.utc).date() - \
                self.create_date.date()
            return str(time.days // 7) + '주'
        else:
            return f"{self.create_date.year}년 {self.create_date.month}월 {self.create_date.day}일"

instagram/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth import update_session_auth_hash
from django.db.models import Count
from .models import *
from .forms import *
from collections import deque


def text_to_hashtag(texts):
    texts = texts.lower()
    texts = texts.split("\r\n")
    tags = []
    comments = []

    for text in texts:
        tagging = False
        temp = []
        q = deque(text)
        while q:
            x = q.popleft()

            if x == "#":
                if tagging:
                    comments.append(temp)
                temp = ["#"]
                tagging = True
            elif x == " ":
                if tagging and len(temp) > 1:
                    tags.append(temp)
                else:
                    temp.append(x)
                    comments.append(temp)
                temp = []
                tagging = False
            else:
                temp.append(x)

        if temp:
            if temp[0] == "#" and len(temp) > 1:
                tags.append(temp)
            else:
                comments.append(temp)

        if comments and comments[-1] != ["\n"]:
            comments.append(["\n"])

    return tags, comments


@login_required
def index(request):
    if request.user.is_authenticated:
        posts = Post.objects.filter(author=request.user)

        followers = []
        for following in request.user.following.all():
            posts |= Post.objects.filter(author=following.follower)
            followers.append(following.follower)

        posts |= Post.objects.filter(author__in=followers)

        followers = User.objects.filter(
            username__in=followers).order_by("-last_login")[:7]

        context = {
            "posts": posts,
            "followers": followers,
        }

        return render(request, "instagram/index.html", context)
    return redirect("registration:login")


@login_required
def post(request):
    if request.method == "POST":
        post = Post.objects.create(
            author=request.user,
            main_image=request.FILES.get('main_image'),
        )
        images = request.FILES.getlist('image')
        for image in images:
            Image.objects.create(post=post, image=image)

        return redirect("instagram:update", pk=post.pk)

    context = {
        "post_form": PostForm,
        "image_form": ImageForm,
    }
    return render(request, "instagram/post.html", context)


@login_required
def update(request, pk):
    post = get_object_or_404(Post, id=pk)
    try:
        images = Image.objects.filter(post=post)
    except:
        images = None

    if request.user == post.author:
        if request.method == "POST":
            for tag in post.posttag_set.all():
                tag.post.remove(post)

            text = request.POST["text"]
            tags, comments = text_to_hashtag(text)
            result = []

            for comment in comments:
                if comment:
                    result.append("".join(comment))

            comment = "".join(result)

            try:
                post_comment = PostComment.objects.get(post=post)
                post_comment.text = comment
                post_comment.save()
            except:
                post_comment = PostComment.objects.create(
                    post=post, text=comment)

            for tag in tags:
                tag = "".join(tag)
                try:
                    tag = PostTag.objects.get(text=tag)
                except:
                    tag = PostTag.objects.create(text=tag)
                finally:
                    tag.post.add(post)

            post.save()
            return redirect("instagram:index")
        else:
            context = {
                "post": post
            }
            try:
                context["post_comment_form"] = PostCommentForm(
                    instance=post.postcomment)
            except:
                context["post_comment_form"] = PostCommentForm

            if images is not None:
                context["images"] = images
            return render(request, "instagram/update.html", context)
    else:
        return redirect("instagram:index")  # 에러 발생


@login_required
def delete(request, pk):
    post = get_object_or_404(Post, id=pk)
    if request.user == post.author:
        post.delete()
        return redirect("instagram:index")
    else:
        return redirect("instagram:index")  # 에러 발생


@login_required
def post_detail(request, pk):
    post = get_object_or_404(Post, id=pk)
    comments = Comment.objects.filter(post=post.id)
    context = {
        "post": post,
        "comments": comments,
        "comment_form": CommentForm,
    }

    try:
        liked = post.like_set.get(user=request.user)
    except:
        liked = None

    if liked:
        context["liked"] = True

    try:
        Follow.objects.get(follower=post.author, following=request.user)
        followed = "True"
    except:
        followed = "False"

    context["followed"] = followed

    return render(request, "instagram/post_detail.html", context)


@login_required
def comment_create(request, pk):
    post = get_object_or_404(Post, id=pk)
    if request.method == "POST":
        text = request.POST["text"]
        tags, comments = text_to_hashtag(text)
        result = []

        for comment in comments:
            if comment:
                result.append("".join(comment))

        result = "".join(result)
        comment = Comment.objects.create(
            author=request.user, post=post, text=result)

        for tag in tags:
            tag = "".join(tag)
            try:
                tag = HashTag.objects.get(text=tag)
            except:
                tag = HashTag.objects.create(text=tag)
            finally:
                tag.comment.add(comment)

    return redirect("instagram:post_detail", pk=pk)


@login_required
def comment_delete(request, pk, comment_pk):
    comment = get_object_or_404(Comment, id=comment_pk)
    if request.user == comment.author:
        comment.delete()
    return redirect("instagram:post_detail", pk=pk)


@login_required
def like(request, pk):
    post = get_object_or_404(Post, id=pk)
    try:
        liked = Like.objects.get(user=request.user, post=post)
        liked.delete()
    except:
        Like.objects.create(user=request.user, post=post)
    finally:
        return redirect("instagram:post_detail", pk=pk)


@login_required
def search(request, search_for):
    target = "tag only"
    context = {
        "search_for": search_for,
        "target": target,
    }

    if not search_for.startswith("#"):
        user_result = User.objects.filter(username__icontains=search_for)
        user_result |= User.objects.filter(profile__name__icontains=search_for)
        user_result = user_result.annotate(
            count=Count("follower")).order_by("-count")

        follow_result = []
        for user_ in user_result:
            try:
                Follow.objects.get(follower=user_, following=request.user)
                follow_result.append(user_)
            except:
                continue

        context["follow_result"] = follow_result
        context["user_result"] = user_result
        context["target"] = "both"

        search_for = "#" + search_for

    post_ids = set()
    hashtags = HashTag.objects.filter(text__iexact=search_for)
    for tag in hashtags:
        for comment in tag.comment.all():
            post_ids.add(comment.post.pk)

    tag_result = Post.objects.filter(id__in=post_ids)

    posttags = PostTag.objects.filter(text__iexact=search_for)
    for tag in posttags:
        tag_result |= tag.post.all()

    tag_result_like = tag_result.order_by("-like", "-create_date")[:6]
    tag_result_date = tag_result.order_by("-create_date")
    context["tag_result_like"] = tag_result_like
    context["tag_result_date"] = tag_result_date

    return render(request, "instagram/search.html", context)


@login_required
def profile(request, username):
    user_ = get_object_or_404(User, username=username)
    following_with_my_following = []
    if request.user != user_:
        for following in request.user.following.all():
            my_following = following.follower
            check = Follow.objects.filter(
                follower=user_, following=my_following)
            if check:
                following_with_my_following.append(my_following)

    try:
        Follow.objects.get(follower=user_, following=request.user)
        followed = "True"
    except:
        followed = "False"

    context = {
        "user_": user_,
        "followed": followed,
        "follow_list": following_with_my_following,
    }
    return render(request, "instagram/profile.html", context)


@login_required
def follow(request, username):
    follower = get_object_or_404(User, username=username)
    following = get_object_or_404(User, username=request.user.username)
    if follower == following:   # 404 발생시키자
        messages.error(request, "자기 자신을 팔로우 할 수 없습니다.")
        return redirect("instagram:index")
    try:
        followed = Follow.objects.get(
            follower=follower, following=following)
        followed.delete()
    except:
        Follow.objects.create(follower=follower, following=following)
    finally:
        return redirect("instagram:profile", username=username)


@login_required
def dm(request):
    return render(request, "instagram/dm.html")


@login_required
def notice(request):
    return render(request, "instagram/notice.html")


@login_required
def profile_edit(request):
    profile = Profile.objects.get(user=request.user)

    if request.method == "POST":
        if "image_change" in request.POST:
            image = request.FILES.get('user_image')
            if image:
                profile.user_image = image
                profile.save()
        else:

instagram/templates/instagram/dm.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
{% include 'base_instagram.html' %}
{% endblock head %}

{% block body %}
<header>
    {% include 'base_header.html' %}
</header>
<main>
    {{ user.username }}
</main>

{% endblock body %}

instagram/templates/instagram/index.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
{% include 'base_instagram.html' %}
<script>
    const user = "{{ user }}";
    const postURL = "{% url 'instagram:post_detail' pk='❤' %}";
    const updateURL = "{% url 'instagram:update' pk='❤' %}";
    const deleteURL = "{% url 'instagram:delete' pk='❤' %}";
    const followURL = "{% url 'instagram:follow' username='❤' %}";
</script>
<script defer src="{% static 'js/index.js' %}"></script>
<script defer src="{% static 'js/toggle_index.js' %}"></script>
{% endblock head %}

{% block body %}
<header>
    {% include 'base_header.html' %}
</header>
<main class="instagram-main">
    <div id="feed">
        <article class="follow-wrapper post-wrapper" id="follower">
            {% for follower in followers %}
            <a href="{% url 'instagram:profile' username=follower %}">
                <div class="follower">
                    <div class="image-box">
                        <img src="{{ follower.profile.user_image.url }}" alt="" class="profile-image">
                    </div>
                    <div class="follower-name">
                        {{ follower }}
                    </div>
                </div>
            </a>
            {% endfor %}
        </article>
        <br>
        <article>
            {% for post in posts.all|dictsortreversed:"create_date" %}
            <section class="post-wrapper">
                <section class="post-top">
                    <div class="post-user feed-post">
                        <div class="image-box">
                            <a href="{% url 'instagram:profile' username=post.author %}">
                                <img src="{{ post.author.profile.user_image.url }}" alt="" class="profile-image"></a>
                        </div>
                        <a href="{% url 'instagram:profile' username=post.author %}"
                            class="user-href">{{ post.author }}</a>
                    </div>
                    <div class="post-btn">
                        <img src="{% static 'image/horiz.png' %}" data-id-one="{{ post.author }}"
                            data-id-two="{{ post.pk }}">
                    </div>
                </section>
                <section class="post-mid">
                    <div class="slide-image" id="post-update-bot-left" data-id="{{ post.image_set.all|length }}">
                        <div id="prev-btn"><img src="{% static 'image/prev_btn.png' %}" alt=""></div>
                        <div id="next-btn"><img src="{% static 'image/next_btn.png' %}" alt=""></div>
                        <div id="multiple-container">
                            <div>
                                <img src="{{ post.main_image.url }}" alt="" class="post-image">
                            </div>
                            {% for image in post.image_set.all %}
                            <div>
                                <img src="{{ image.image.url }}" alt="" class="post-image">
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </section>
                <section class="post-bot feed-post">
                    <div class="post-like">좋아요 {{ post.like_set.all|length }}개</div>
                    <div>
                        {% if post.postcomment.text or post.posttag_set.all|length > 0 %}
                        <div class="post-comment">
                            <span class="comment-author">
                                <a href="{% url 'instagram:profile' username=post.author %}"
                                    class="user-href">{{ post.author }}</a>
                            </span>
                            <span class="comment-text">{{ post.postcomment.text }}
                                {% for tag in post.posttag_set.all %}
                                <a href="{% url 'instagram:search' search_for=tag.text %}"
                                    class="hash-tag-href">{{ tag.text }}</a>{% endfor %}
                            </span>
                        </div>
                        {% for comment in post.comment_set.all|slice:":2" %}
                        <div class="post-comment">
                            <span class="comment-author">
                                <a href="{% url 'instagram:profile' username=comment.author %}"
                                    class="user-href">{{ comment.author }}</a>
                            </span>
                            <span class="comment-text">
                                {{ comment.text }}
                                {% for tag in comment.hashtag_set.all %}
                                <a href="{% url 'instagram:search' search_for=tag.text %}"
                                    class="hash-tag-href">{{ tag.text }}</a>{% endfor %}
                            </span>
                        </div>
                        {% endfor %}
                        {% else %}
                        {% for comment in post.comment_set.all|slice:":3" %}
                        <div class="post-comment">
                            <span class="comment-author">
                                <a href="{% url 'instagram:profile' username=comment.author %}"
                                    class="user-href">{{ comment.author }}</a>
                            </span>
                            <span class="comment-text">
                                {{ comment.text }}
                                {% for tag in comment.hashtag_set.all %}
                                <a href="{% url 'instagram:search' search_for=tag.text %}"
                                    class="hash-tag-href">{{ tag.text }}</a>{% endfor %}
                            </span>
                        </div>
                        {% endfor %}
                        {% endif %}
                    </div>
                    <div class="post-create-date">
                        <a href="{% url 'instagram:post_detail' pk=post.pk %}">
                            {{ post.postcomment.create_date_string }}{% if post.postcomment.create_date != post.postcomment.update_date %}(수정됨){% endif %}
                        </a>
                    </div>
                </section>
            </section>
            <br>
            {% endfor %}
        </article>
    </div>
</main>
<aside>
    <a href="{% url 'instagram:profile' username=user.username %}">{{ user.username}}</a>
    {% for message in messages %}
    {{ message.tags }}
    {{ message.message }}
    {% endfor %}
</aside>

{% endblock body %}

instagram/templates/instagram/notice.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
{% include 'base_instagram.html' %}
{% endblock head %}

{% block body %}
<header>
    {% include 'base_header.html' %}
</header>
<main>
    {{ user.username }}
</main>

{% endblock body %}

instagram/templates/instagram/post_detail.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
{% include 'base_instagram.html' %}
<script>
    const user = "{{ user }}";
    const isFollowing = "{{ followed }}";
    const postURL = "{% url 'instagram:post_detail' pk=post.pk %}";
    const updateURL = "{% url 'instagram:update' pk=post.pk %}";
    const deleteURL = "{% url 'instagram:delete' pk=post.pk %}";
    const followURL = "{% url 'instagram:follow' username=post.author %}";
    const commentURL = "{% url 'instagram:comment_delete' pk=post.pk comment_pk='❤' %}";
</script>
<script defer src="{% static 'js/toggle_post.js' %}"></script>
{% endblock head %}

{% block body %}
<header>
    {% include 'base_header.html' %}
</header>
<main class="instagram-main">
    <article class="post-wrapper post-detail">
        <section class="post-left">
            <img src="{{ post.main_image.url }}" alt="" class="post-image">
        </section>
        <section class="post-right">
            <section class="post-top">
                <div class="post-user feed-post">
                    <div class="image-box">
                        <a href="{% url 'instagram:profile' username=post.author %}">
                            <img src="{{ post.author.profile.user_image.url }}" alt="" class="profile-image"></a>
                    </div>
                    <a href="{% url 'instagram:profile' username=post.author %}" class="user-href">{{ post.author }}</a>
                </div>
                <div class="post-btn">
                    <img src="{% static 'image/horiz.png' %}" data-id-one="{{ post.author }}"
                        data-id-two="{{ post.pk }}">
                </div>
            </section>
            <section class="post-mid border-light-top">
                {% if post.postcomment.text or post.posttag_set.all|length > 0 %}
                <div class="post-user feed-post">
                    <div class="image-box">
                        <a href="{% url 'instagram:profile' username=post.author %}">
                            <img src="{{ post.author.profile.user_image.url }}" alt="" class="profile-image"></a>
                    </div>
                    <div class="comment-div">
                        <div>
                            <a href="{% url 'instagram:profile' username=post.author %}"
                                class="user-href">{{ post.author }}</a>
                            <span class="comment-text">
                                {{ post.postcomment.text }}
                                {% for tag in post.posttag_set.all %}
                                <a href="{% url 'instagram:search' search_for=tag.text %}"
                                    class="hash-tag-href">{{ tag.text }}</a>
                                {% endfor %}
                            </span>
                        </div>
                        <div class="comment-create-date">
                            {{ post.create_date_string }}
                        </div>
                    </div>
                </div>
                {% endif %}
                {% for comment in comments %}
                <div class="post-user feed-post">
                    <div class="image-box">
                        <a href="{% url 'instagram:profile' username=comment.author %}">
                            <img src="{{ comment.author.profile.user_image.url }}" alt="" class="profile-image"></a>
                    </div>
                    <div class="comment-div">
                        <div>
                            <a href="{% url 'instagram:profile' username=comment.author %}"
                                class="user-href">{{ comment.author }}</a>
                            <span class="comment-text">
                                {{ comment.text }}
                                {% for tag in comment.hashtag_set.all %}
                                <a href="{% url 'instagram:search' search_for=tag.text %}"
                                    class="hash-tag-href">{{ tag.text }}</a>{% endfor %}
                            </span>
                        </div>
                        <div class="comment-create-date">
                            {{ comment.create_date_string }}
                            {% if comment.author == user %}
                            <span class="comment-btn">
                                <img src="{% static 'image/horiz.png' %} " data-id-one="{{ comment.pk }}">
                            </span>
                            {% endif %}
                        </div>
                    </div>
                </div>
                {% endfor %}
            </section>
            <section class="post-bot">
                <div class="border-light-top post-bot-top">
                    <div class="image-box">
                        <a href="{% url 'instagram:like' pk=post.pk %}">
                            {% if liked %}
                            <img src="{% static 'image/notice_black.png' %}" alt="" class="profile-image">
                            {% else %}
                            <img src="{% static 'image/notice.png' %}" alt="" class="profile-image">
                            {% endif %}
                        </a>
                    </div>
                    <div class="post-like">좋아요 {{ post.like_set.all|length }}개</div>
                    <div class="post-create-date">
                        {{ post.postcomment.create_date_string }}{% if post.postcomment.create_date != post.postcomment.update_date %}(수정됨){% endif %}
                    </div>
                </div>
                <form action="{% url 'instagram:comment_create' pk=post.pk %}" method="POST"
                    class="post-bot-bot border-light-top">
                    {% csrf_token %}
                    {{ comment_form }}
                    <input type="submit" value="게시">
                </form>
            </section>
        </section>
    </article>
</main>

{% endblock body %}