instagram/urls.py
from django.urls import path
from . import views

app_name = "instagram"
urlpatterns = [
    path("", views.index, name="index"),
    path("post/", views.post, name="post"),
    path("update/<pk>/", views.update, name="update"),
    path("delete/<pk>/", views.delete, name="delete"),
    path("post_detail/<pk>/", views.post_detail, name="post_detail"),
    path("post_detail/<pk>/comment_create",
         views.comment_create, name="comment_create"),
    path("post_detail/<pk>/comment_delete/<comment_pk>/",
         views.comment_delete, name="comment_delete"),
    path("post_detail/<pk>/like/", views.like, name="like"),
    path("search/<search_for>", views.search, name="search"),
    path("profile/<username>/", views.profile, name="profile"),
    path("profile/<username>/follow/", views.follow, name="follow"),
    path("dm/", views.dm, name="dm"),
    path("notice/", views.notice, name="notice"),
    path("profile_edit/", views.profile_edit, name="profile_edit"),
    path("profile_edit/reset_profile_image",
         views.reset_profile_image, name="reset_profile_image"),
    path("change_password/", views.change_password, name="change_password"),
]

registration/urls.py
from django.urls import path
from . import views

app_name = "registration"
urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("delete_account/", views.delete_account, name="delete_account"),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% include 'base_head.html' %}
    {% block head %}{% endblock head %}
</head>

<body>
    {% block body %}{% endblock body %}
</body>

</html>

templates/base_footer.html
<div>footer</div>
<div>footer</div>
<div>footer</div>
<div>footer</div>

templates/base_head.html
{% load static %}
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<title>Instagram{% if user_ %} | {{ user_.username }}{% endif %}</title>

templates/base_header.html
{% load static %}
<article>
    <script defer>
        const searchURL = "{% url 'instagram:search' search_for='❤' %}"
    </script>
    <a href="{% url 'instagram:index' %}" id="header-one" class="instagram-image"><img
            src="{% static 'image/instagram_small.png' %}" tabindex="0"></a>
    <div id="header-two">
        <form id="search-form">
            <a href="" id="search-href"></a>
            <input type="search" name="search_for" placeholder="🔍검색" required id="search-input">
            <input type="submit" id="search-btn" hidden>
        </form>
    </div>
    <nav id="header-three">
        <div class="instagram-image nav-div">
            {% if request.path == "/instagram/" %}
            <a href="{% url 'instagram:index' %}"><img src="{% static 'image/home_black.png' %}"></a>
            {% else %}
            <a href="{% url 'instagram:index' %}"><img src="{% static 'image/home.png' %}"></a>
            {% endif %}
        </div>
        <div class="instagram-image nav-div">
            {% if request.path == "/instagram/dm/" %}
            <a href="{% url 'instagram:dm' %}"><img src="{% static 'image/dm_black.png' %}"></a>
            {% else %}
            <a href="{% url 'instagram:dm' %}"><img src="{% static 'image/dm.png' %}"></a>
            {% endif %}
        </div>
        <div class="instagram-image nav-div">
            {% if request.path == "/instagram/notice/" %}
            <a href="{% url 'instagram:notice' %}"><img src="{% static 'image/notice_black.png' %}"></a>
            {% else %}
            <a href="{% url 'instagram:notice' %}"><img src="{% static 'image/notice.png' %}"></a>
            {% endif %}
        </div>
        <div class="instagram-image nav-div">
            <a href="{% url 'instagram:post' %}"><img src="{% static 'image/posting.png' %}"></a>
        </div>
        <div class="nav-div">
            <a href="{% url 'instagram:profile' username=user.username %}" id="nav-profile">
                <div class="image-box">
                    <img src="{{ user.profile.user_image.url }}" class="profile-image">
                </div>
            </a>
            <ul class="nav-menu" id="nav-profile-menu">
                <a href="{% url 'instagram:profile' username=user.username %}">
                    <li>프로필</li>
                </a>
                <hr>
                <a href="{% url 'registration:logout' %}">
                    <li>로그아웃</li>
                </a>
            </ul>
        </div>
    </nav>
</article>

templates/base_instagram.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/instagram.css' %}">
<script defer src="{% static 'js/profile_menu.js' %}"></script>

templates/base_registration.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/registration.css' %}">